name: Deploy to GCP

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup Google Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Create GCP Bucket if it doesn't exist
      run: |
        BUCKET_NAME="tatenda_magaisa_site"

        # Check if the bucket already exists
        if ! gsutil ls "gs://${BUCKET_NAME}"; then
          # Create the bucket if it doesn't exist
          gsutil mb -l us-central1 "gs://${BUCKET_NAME}"
        fi
      env:
        NODE_ENV: production

    - name: Build and deploy
      run: |
        # Deploy to Google Cloud Storage
        gsutil -m rsync -r ./ gs://tatenda_magaisa_site
